Makefile: add init, start, stop targets for privnet
bane-labs/go-ethereum pull request #10
Opened 2023-09-09 20:15 UTC by tatiana-nspcc

The corrected instructions for running a private Ethereum network (privnet) have been placed in `privnet/README.md`.

Close #8

2023-09-11 13:16 UTC, AnnaShaleva requested changes
After the setup structure is settle, we need to add the documentation on how to use these new `make` targets and how to start the privnet network and connect some local node to it. We also need to add the GH action that will check that building targets work as expected, exactly like NeoGo's https://github.com/nspcc-dev/neo-go/blob/master/.github/workflows/build.yml.

2023-09-11 13:16 UTC, AnnaShaleva commented on .gitignore
> +/prnet/
s/prnet/privnet everywhere to make it unified with NeoGo privnet setup?

2023-09-11 13:16 UTC, AnnaShaleva commented on Makefile
> +	$(call create_account,$(NODE2))
We don't need new accounts each time the privnet is being setup. Make it once, add these ready-to-use accounts into some repo folder like it is done for NeoGo and use them to run the privnet afterwards. If needed, you can write instructions on how to generate proper accounts, but we need solid constant accounts every privnet run. It will be useful for testing and debugging.

2023-09-11 13:16 UTC, AnnaShaleva commented on Makefile
> +	$(call replace_chainid)
The same comment is relevant for the chain ID and genesis file, I doubt we need new data each time the network is started. @roman-khimov?

2023-09-11 13:16 UTC, AnnaShaleva commented on Makefile
> +prnet_init: prnet_clean
How about `env_single`, `env_up`, `env_down` and `env_clean` to match the NeoGo pattern? See the https://github.com/nspcc-dev/neo-go/blob/2d88ed9fe5d58cd77280aa07c5b4fa95d5092abf/Makefile#L136 and related targets.

2023-09-11 13:16 UTC, AnnaShaleva commented on Makefile
> +	@echo "OK! Check logs in <node_dir>/geth_node.log"
So we don't use Docker for it. Are you sure we'd like to have these nodes running directly on the host machine? I'd suggest to dockerize the privnet network creation from scratch, have a separate configuration file for node2 under some `config` directory and start the single Geth node as docker network, exactly like in NeoGo. This allows to extend the network configuration in future.

2023-09-11 13:16 UTC, AnnaShaleva commented on Makefile
> +prnet_init: prnet_clean
And BTW, these new targets are all `.PHONY`.

2023-09-11 13:16 UTC, AnnaShaleva commented on Makefile
> +	@echo "OK! Check logs in <node_dir>/geth_node.log"
@roman-khimov?

2023-09-11 13:16 UTC, AnnaShaleva commented on genesis_base.json
> +{
We need to put this file in a special directory and add some `privnet` suffix.

2023-09-11 13:16 UTC, AnnaShaleva commented on genesis_base.json
> +}
No new line in the end of the file.

2023-09-11 13:19 UTC, AnnaShaleva commented
Don't forget to add `Close #8` message to PR description or commit description.

2023-09-12 08:45 UTC, tatiana-nspcc commented on Makefile
> +	@echo "OK! Check logs in <node_dir>/geth_node.log"
@roman-khimov asked me not to use Docker if possible. So, here we are.

2023-09-12 08:45 UTC, tatiana-nspcc commented on Makefile
> +prnet_init: prnet_clean
There's no "single" environment. It starts with two nodes from the beginning. Also, I don't use Docker, so I think it's different from the NeoGo project. 
If you really want to, we should replace "single" with "init," at least.

2023-09-12 08:45 UTC, tatiana-nspcc commented on Makefile
> +	$(call replace_chainid)
The same idea applies here. Just use privnet_stop and privnet_start without privnet_init, and you'll get the same chain ID.

2023-09-12 08:45 UTC, tatiana-nspcc commented on Makefile
> +	$(call create_account,$(NODE2))
You don't need to generate it each time. As you can see, there are two steps to start privnet: `privnet_init` and `privnet_start`. The first time, you need both of them, but afterward, use only `privnet_stop` and `privnet_start` to use the same privnet without generating new accounts.
Even more than that, I don't want to store passwords on GitHub. I believe it's bad practice. So, I've written a generator.

2023-09-12 12:36 UTC, AnnaShaleva commented on Makefile
> +	$(call create_account,$(NODE2))
IMO, we need a reproducible environment and solid addresses at every local machine every time when you clone the repo or checkout wallet changes. What we literally need is to generate these accounts once and store them in some folder like it is done for NeoGo privnet wallets (https://github.com/nspcc-dev/neo-go/tree/master/.docker/wallets). It's development privnet, no one cares about accounts/passwords safety here.

What we may have additionally is some `regenerate_wallets_test.go` test that regenerates privnet wallets or instructions inside the README file or at some other documentation file that describes how to regenerate these wallets. We even can go with this separate make target, but we don't need to call it each time on new setup.

2023-09-12 12:42 UTC, AnnaShaleva commented on Makefile
> +prnet_init: prnet_clean
Well, my concern was about `prnet` mostly, it looks strange a bit, I got used to `privnet` or `env` in our projects.

2023-09-12 12:42 UTC, AnnaShaleva commented on Makefile
> +	@echo "OK! Check logs in <node_dir>/geth_node.log"
OK.

2023-09-12 13:06 UTC, tatiana-nspcc commented on Makefile
> +	$(call create_account,$(NODE2))
Account's addresses and keys are stored in separate files, so we can use them in tests. And in case of regenerating we don't need to update hard-coded config.

2023-09-12 13:17 UTC, roman-khimov commented on Makefile
> +	$(call create_account,$(NODE2))
Static keys are easier to handle for test environments. You can keep this logic in case we need to recreate them, but in general static well-known wallets are OK for this particular purpose (it's not production keys). We do this in NeoGo, NeoFS dev-env, AIO. Makes things more predictable.

2023-09-12 13:19 UTC, roman-khimov commented on Makefile
> +	$(call replace_chainid)
We better be aligned wrt these values between different instances, hardcoding them is OK. Again, see dev-env, AIO, NeoGo privnets.

Just to reiterate, it's a test environment, we're not trying to create some production networks here.

2023-09-18 07:35 UTC, AnnaShaleva commented on privnet/node1/geth/chaindata/ancient/chain/bodies.meta
> +��
Please, add `chaindata` to .gitignore :)

2023-09-18 09:06 UTC, AnnaShaleva reviewed
@tatiana-nspcc, looks better, you got the idea right. Finish your current tasks and re-request review, I'll review one more time and try to run it locally.

2023-09-18 09:06 UTC, AnnaShaleva commented on .github/workflows/tests.yml
> +          go-version: '1.18'
Minimum supported Go version for this project is 1.19. And let's use go 1.21 for this, as suggested in https://github.com/ethereum/go-ethereum/blob/90d5bd85bcf2919ac2735a47fde675213348a0a6/.travis.yml#L12.

2023-09-18 09:06 UTC, AnnaShaleva commented on .github/workflows/tests.yml
> +        go_versions: [ '1.18', '1.19', '1.20' ]
Remove 1.18, add 1.21.

2023-09-18 09:06 UTC, AnnaShaleva commented on .github/workflows/tests.yml
> +        os: [ubuntu-20.04, windows-2022, macos-12]
Well, I'm not sure we need tests for Windows and macOS, although they are supported by the geth. Check out the way how they run tests, it's only for linux distributives: https://github.com/ethereum/go-ethereum/blob/90d5bd85bcf2919ac2735a47fde675213348a0a6/.travis.yml#L108

2023-09-18 09:06 UTC, AnnaShaleva commented on .github/workflows/tests.yml
> +name: Tests
We also need a building workflow, it should be run on Ubuntu and it should use `make geth`. Check out the way how NeoGo `Build CLI` GA job works.

2023-09-18 09:06 UTC, AnnaShaleva commented on privnet/bootnode.log
> +enode://0cfebf0ca4056001706eb6c793ed29ce8626b51c940ae12db2eb419d5914dfe7926399ff87a4b85165d2bb5ff3704c906ee45004b4f3573ba415fd168470312d@127.0.0.1:0?discport=30305
We don't need this log to be included in git, do we?

2023-09-18 09:06 UTC, AnnaShaleva commented on privnet/genesis_base.json
> +{
Let's change the file name to `genesis_template.json`?

2023-09-18 09:06 UTC, AnnaShaleva commented on privnet/genesis_privnet.json
> +{
What is the purpose of `privnet/genesis_privnet.json` while we have `privnet/node1/genesis_privnet.json` and `privnet/node2/genesis_privnet.json`?

2023-09-18 09:06 UTC, AnnaShaleva commented on privnet/node1/geth_create_account.log
> +INFO [09-17|17:10:08.866] Maximum peer count                       ETH=50 LES=0 total=50
I doubt we need this file as far. Please, add all unnecessary files to .gitignore.

2023-09-18 09:08 UTC, tatiana-nspcc commented on .gitignore
> +/prnet/
Changed.

2023-09-18 09:09 UTC, tatiana-nspcc commented on Makefile
> +prnet_init: prnet_clean
Thanks, fixed.

2023-09-18 09:09 UTC, tatiana-nspcc commented on genesis_base.json
> +{
Moved it into `privnet` directory

2023-09-18 09:10 UTC, tatiana-nspcc commented on genesis_base.json
> +}
Added.

2023-09-18 09:26 UTC, tatiana-nspcc commented on Makefile
> +prnet_init: prnet_clean
`prnet` was changed to `privnet`.

2023-09-18 09:46 UTC, AnnaShaleva commented on .github/workflows/tests.yml
> +name: Tests
The last step in this job will be:
```
      - name: Build node
        run: make geth
```

2023-09-19 20:18 UTC, tatiana-nspcc commented on privnet/node1/geth/chaindata/ancient/chain/bodies.meta
> +��
I checked, I can't start privnet without this directory.

2023-09-19 20:24 UTC, tatiana-nspcc commented on privnet/genesis_privnet.json
> +{
The triple copy of the `genesis.json` file was mentioned in https://geth.ethereum.org/docs/fundamentals/private-network. It's required to init a new privnet, and it won't work without it. I've added it to `.gitignore`.

2023-09-19 21:42 UTC, tatiana-nspcc commented on Makefile
> +	$(call create_account,$(NODE2))
Okay, I've added privnet/config.json with addresses, passwords, and chain_id.

2023-09-19 21:43 UTC, tatiana-nspcc commented on Makefile
> +	$(call replace_chainid)
Okay, I've added privnet/config.json with addresses, passwords, and chain_id.

2023-09-19 21:43 UTC, tatiana-nspcc commented on .github/workflows/tests.yml
> +          go-version: '1.18'
Fixed.

2023-09-19 21:43 UTC, tatiana-nspcc commented on .github/workflows/tests.yml
> +        go_versions: [ '1.18', '1.19', '1.20' ]
Fixed.

2023-09-19 21:44 UTC, tatiana-nspcc commented on .github/workflows/tests.yml
> +        os: [ubuntu-20.04, windows-2022, macos-12]
I'm leaving only `ubuntu-20.04` here.

2023-09-19 21:44 UTC, tatiana-nspcc commented on .github/workflows/tests.yml
> +name: Tests
Added `build.yaml`

2023-09-19 21:45 UTC, tatiana-nspcc commented on privnet/bootnode.log
> +enode://0cfebf0ca4056001706eb6c793ed29ce8626b51c940ae12db2eb419d5914dfe7926399ff87a4b85165d2bb5ff3704c906ee45004b4f3573ba415fd168470312d@127.0.0.1:0?discport=30305
Added to `.gitignore`.

2023-09-19 21:45 UTC, tatiana-nspcc commented on privnet/genesis_base.json
> +{
Ok, changed.

2023-09-19 21:45 UTC, tatiana-nspcc commented on privnet/node1/geth_create_account.log
> +INFO [09-17|17:10:08.866] Maximum peer count                       ETH=50 LES=0 total=50
Added to `.gitignore`.

2023-09-20 07:52 UTC, AnnaShaleva commented on privnet/node1/geth/chaindata/ancient/chain/bodies.meta
> +��
How about adding the content of `chaindata`? We can have some files that are really necessary for the node run, but we don't need the full DB to be stored in git.

2023-09-20 13:45 UTC, tatiana-nspcc commented on privnet/node1/geth/chaindata/ancient/chain/bodies.meta
> +��
If you mean keeping the empty directory `privnet/node1/geth/chaindata/`, that can also cause problems. Perhaps for now, the better solution is to leave it as it is and sort through the essential and unnecessary files later?

2023-09-20 13:55 UTC, tatiana-nspcc commented
In the last force push I rebased the branch on the fresh `bane-main` state and corrected the spelling of `bane-main` in the workflows.

2023-09-21 10:53 UTC, AnnaShaleva commented on privnet/node1/geth/chaindata/ancient/chain/bodies.meta
> +��
What I mean is to add to leave some files that are really necessary for the node run from scratch and add to .gitignore and remove the others.

>to leave it as it is and sort through the essential and unnecessary files later

The problem with this approach is that these files look like the node's DB files. Thus, these files will be changed on every privnet run. Thus, they will be marked in git as "changed" during the development process, and I'd like to avoid this and to have the git index clean after the subsequent privnet run.

2023-09-21 10:53 UTC, AnnaShaleva commented on privnet/README.md
> +
We're building the development privnet, thus it is expected that the following sequens of commands will work:
```
$ cd go-ethereum
$ make geth
$ make privnet_start
```
And currently the result of this sequence is `/bin/sh: 1: geth: not found` in the node logs. That's because we have `geth` binary in the default build folder (in `./build/bin/geth`). What we need is to adjust the Makefile commands so that they run exactly this binary, not just `geth`.

2023-09-21 10:53 UTC, AnnaShaleva commented on .github/workflows/build.yml
> +        os: [{ name: ubuntu-20.04, bin-name: linux }]
You don't need `bin-name`.

2023-09-21 10:53 UTC, AnnaShaleva commented on .gitignore
> +/privnet/genesis_privnet.json
Then we don't need `genesis_privnet.json` to be ignored, otherwise we won't be able to commit the result of `make privnet_init` on chain regeneration.

2023-09-21 10:53 UTC, AnnaShaleva commented on .gitignore
> +/privnet/node2/geth_create_account.log
We need to ignore all logs that are changed from run to run. E.g. ignore `privnet/node1/geth_node.log` and etc. Try to ignore `*.log` files except the ones that are really necessary.

2023-09-21 11:01 UTC, AnnaShaleva commented on Makefile
> +	@bootnode -genkey $(MAIN_DIR)/bootnode.key
@tatiana-nspcc, could you, please, provide the link to `bootnode` command? It's not in the `Build from source code` section of https://geth.ethereum.org/docs/getting-started/installing-geth (we're interested in it as a developers), and it's not a part of the `geth` itself AFAIU.

2023-09-21 11:07 UTC, tatiana-nspcc commented on Makefile
> +	@bootnode -genkey $(MAIN_DIR)/bootnode.key
Yes, for sure, it's link from the `README.md` file: https://geth.ethereum.org/docs/fundamentals/private-network section `End-to-end example`.

2023-09-21 18:24 UTC, tatiana-nspcc commented on privnet/README.md
> +
Fixed `README.md` file and `Makefile` accordingly to this comment.

2023-09-21 18:24 UTC, tatiana-nspcc commented on .github/workflows/build.yml
> +        os: [{ name: ubuntu-20.04, bin-name: linux }]
Fixed.

2023-09-21 18:24 UTC, tatiana-nspcc commented on .gitignore
> +/privnet/genesis_privnet.json
Fixed.

2023-09-21 18:24 UTC, tatiana-nspcc commented on .gitignore
> +/privnet/node2/geth_create_account.log
Fixed.

2023-09-22 11:20 UTC, AnnaShaleva commented on Makefile
> +privnet_init_: privnet_clean
Remove this target, we already have `privnet_init`, it does all the things properly. As discussed earlier, "Init nodes" step shouldn't be performed at the `privnet_init` stage.

2023-09-22 11:20 UTC, AnnaShaleva commented on Makefile
> +	@echo "OK! Check logs in privnet/<node_dir>/geth_node.log"
We don't need two targets for the same action. As discussed, what we need is "Init nodes" stage to be presented in `privnet_start` target (like it is done currently), but we also need to add a condition to skip nodes initialization in case if the DB is already initialized. That's exactly the purpose `make` is designed for.

And after that `privnet_start_` should be removed.

2023-09-22 11:20 UTC, AnnaShaleva commented on Makefile
> +endef
We don't need this definition. You have `genesis_template.json`, just copy it and replace all necessary data inside it.

2023-09-22 11:20 UTC, AnnaShaleva commented on Makefile
> +    @geth init --datadir $(MAIN_DIR)/$(1)  $(MAIN_DIR)/$(GENESIS_WORK_JSON) > $(MAIN_DIR)/$(1)/geth_init.log 2>&1
```suggestion
    @geth init --datadir $(MAIN_DIR)/$(1) $(MAIN_DIR)/$(GENESIS_WORK_JSON) > $(MAIN_DIR)/$(1)/geth_init.log 2>&1
```

2023-09-22 11:20 UTC, AnnaShaleva commented on Makefile
> +endef
Why it's `miner_node`? We need `signer_node`, because we run a Clique.

And we need the following syntax here:
```
geth <other-flags> --unlock 0x7df9a875a174b3bc565e6424a0050ebc1b2d1d82 --mine
```

2023-09-22 11:20 UTC, AnnaShaleva commented on privnet/README.md
> +```
OK, then it's not enough, because we use a separate bootnode proces (not the fully-qualified node) for it. Thus, we need to build the bootnode binary. Thus, we need to use `make all` instead of just `make geth`.

2023-09-22 11:20 UTC, AnnaShaleva commented on privnet/README.md
> +(privnet):
Add `with Clique as a consensus algorithm.`.

2023-09-22 11:20 UTC, AnnaShaleva commented on privnet/README.md
> +Here are the corrected instructions for running a private Ethereum network
Remove `corrected`?

2023-09-22 11:20 UTC, AnnaShaleva commented on privnet/README.md
> +(privnet):
Add the description of the network, i.e. enumerate its components: bootnode service, Clique consensus node and a simple RPC node.

2023-09-22 11:20 UTC, AnnaShaleva commented on privnet/README.md
> +
Add step 5 about cleaning the private network.

2023-09-22 11:20 UTC, AnnaShaleva commented on .gitignore
> +/privnet/node2/geth/
No new line in the end of the file.

2023-09-22 11:20 UTC, AnnaShaleva commented on .gitignore
> +/privnet/bootnode.log
Create a separate folder for bootnode-related files and logs, please.

2023-09-22 11:20 UTC, AnnaShaleva commented on privnet/genesis_privnet.json
> +{
>The triple copy of the genesis.json file was mentioned

The documentation says only `In each data directory save a copy of the following genesis.json to the top level project directory. `. Both node1 and node2 have their own copy of `genesis.json` files, and the bootnode service doesn't need this. So I'm still not sure we need this file here.

2023-09-22 11:20 UTC, AnnaShaleva commented on .github/workflows/build.yml
> +        run: make geth
Let's do `make all` as we use other services as far.

2023-09-22 11:20 UTC, AnnaShaleva commented on .github/workflows/build.yml
> +    name: Build geth
s/`Build geth`/`Build geth and services`.

2023-09-22 11:20 UTC, AnnaShaleva commented on Makefile
> +privnet_start:
`privnet_start` still won't work after `make all` because of the wrong executable paths. Correct them, please. (paths to `geth` and `bootnode` executable).

2023-09-22 11:21 UTC, AnnaShaleva commented on privnet/README.md
> +
The second part is not fixed yet.

2023-09-22 11:44 UTC, tatiana-nspcc commented on Makefile
> +privnet_init_: privnet_clean
Oops, yes, this target shouldn't be in this commit.

2023-09-22 11:44 UTC, tatiana-nspcc commented on Makefile
> +	@echo "OK! Check logs in privnet/<node_dir>/geth_node.log"
Yes, this one is also my fault.

2023-09-22 11:50 UTC, tatiana-nspcc commented on Makefile
> +endef
I can't put passwords in the `genesis_template.json`. Do you just want to keep them in separate files like `password.txt`? I thought that you wanted to collect and store this data in one file.

2023-09-22 16:54 UTC, AnnaShaleva commented on Makefile
> +endef
I've confused this file with the base genesis json config, so this comment is irelevant, let's keep it as is.

2023-09-25 08:23 UTC, tatiana-nspcc commented on privnet/genesis_privnet.json
> +{
You are right. I misread it, tried again and remove it.

2023-09-25 08:24 UTC, tatiana-nspcc commented on privnet/README.md
> +
Sorry, some wrong or non-final commit was pushed. I fixed it.

2023-09-25 08:24 UTC, tatiana-nspcc commented on Makefile
> +    @geth init --datadir $(MAIN_DIR)/$(1)  $(MAIN_DIR)/$(GENESIS_WORK_JSON) > $(MAIN_DIR)/$(1)/geth_init.log 2>&1
Fixed.

2023-09-25 08:25 UTC, tatiana-nspcc commented on privnet/README.md
> +```
Replaced to `make all`.

2023-09-25 08:27 UTC, tatiana-nspcc commented on privnet/README.md
> +(privnet):
I rewrote this part.

2023-09-25 08:29 UTC, tatiana-nspcc commented on privnet/README.md
> +(privnet):
Done.

2023-09-25 08:29 UTC, tatiana-nspcc commented on privnet/README.md
> +Here are the corrected instructions for running a private Ethereum network
Removed. I meant that these instructions are different from the original end-to-end example. But it wasn't clear, so I rewrote the entire section.

2023-09-25 08:30 UTC, tatiana-nspcc commented on .gitignore
> +/privnet/node2/geth/
Fixed.

2023-09-25 08:31 UTC, tatiana-nspcc commented on .gitignore
> +/privnet/bootnode.log
Done

2023-09-25 08:31 UTC, tatiana-nspcc commented on .github/workflows/build.yml
> +        run: make geth
Replaced to `make all`.

2023-09-25 08:32 UTC, tatiana-nspcc commented on Makefile
> +privnet_start:
Sorry, fixed.

2023-09-25 08:32 UTC, tatiana-nspcc commented on privnet/README.md
> +
Added. But in my opinion, it shouldn't be used separately; it's needed for make privnet_init to re-init privnet.

2023-09-25 08:57 UTC, AnnaShaleva commented
@tatiana-nspcc, if everything except the https://github.com/bane-labs/go-ethereum/pull/10#discussion_r1334223842 is fixed, then let's move on to have some initial implementation of https://github.com/bane-labs/go-ethereum/issues/11. I'll review this PR one more time and experiment with setups a bit later.

2023-09-25 09:37 UTC, tatiana-nspcc commented on Makefile
> +endef
It works as you have written. I checked `miner.etherbase` parameter, it doesn't work without it, the error is:
```
ERROR[09-25|10:30:50.624] Cannot start mining without etherbase    err="etherbase must be explicitly specified"
Fatal: Failed to start mining: etherbase missing: etherbase must be explicitly specified

```

2023-09-26 11:04 UTC, AnnaShaleva commented
@roman-khimov, could you review, please?

2023-09-26 12:19 UTC, tatiana-nspcc reviewed
I appreciate your valuable contribution to this PR. It looks great, especially the addition of 400 lines of minimal instructions in README.md :)

2023-09-26 12:19 UTC, tatiana-nspcc commented on Makefile
Typos in the commit message: prcesses

2023-09-26 12:19 UTC, tatiana-nspcc commented on Makefile
> +    @$(GOBIN)/geth --datadir $(MAIN_DIR)/$(1) account new --password $(MAIN_DIR)/$(1)/password.txt
Typo in the commit message: goot

2023-09-26 12:19 UTC, tatiana-nspcc commented on Makefile
> +	@echo $$($(GOBIN)/bootnode --writeaddress -nodekey $(MAIN_DIR)/$(BOOTNODE)/bootnode.key) > $(MAIN_DIR)/$(BOOTNODE)/bootnode_address.txt
Could you please clarify what issues you encountered with it not working properly? I'm asking in a general sense because it appears to be functioning correctly on my local computer. I have noticed some mistakes in the file writing process.

2023-09-26 13:13 UTC, AnnaShaleva commented on Makefile
> +	@echo $$($(GOBIN)/bootnode --writeaddress -nodekey $(MAIN_DIR)/$(BOOTNODE)/bootnode.key) > $(MAIN_DIR)/$(BOOTNODE)/bootnode_address.txt
> appears to be functioning correctly on my local computer

That's true, it worked with the old `make privnet_clean` scheme when you removed the whole `privnet` directory except a couple of files. And now `privnet_clean` has different behaviour, it cleans only the DB files and keeps all network configuration settings so that the user is ab;e to clean the DB and start the new chain from the genesis with the old settings. It is needed for development and this scheme matches the one we have in NeoGo/AIO/NeoFS devenv.

Thus, we have to replace the existing content of mentioned config files on `make privnet_init`, not just append to it.

2023-09-26 13:13 UTC, AnnaShaleva commented on Makefile
> +    @$(GOBIN)/geth --datadir $(MAIN_DIR)/$(1) account new --password $(MAIN_DIR)/$(1)/password.txt
Fixed.

2023-09-26 13:13 UTC, AnnaShaleva commented on Makefile
Fixed.

2023-09-26 13:14 UTC, AnnaShaleva approved these changes

2023-09-26 13:15 UTC, AnnaShaleva commented
@tatiana-nspcc, agree to merge?

2023-09-26 14:47 UTC, tatiana-nspcc commented
> @tatiana-nspcc, agree to merge?

@AnnaShaleva, Yes!

2023-09-26 15:17 UTC, merged