Add governance and policy contracts
bane-labs/go-ethereum pull request #7
Opened 2023-09-01 10:09 UTC by chenquanyu

This PR is a code implementation of #2, #3, #5. Close #2, Close #3, Close #5. 

This PR is going to add the `Governance` contract to manage consensus list, `Policy` contract to manage policy parameters. We will have the first Phase of consensus in genesis block and the users can vote for new Phases with GAS in `Governance` contract. The `GovReward` contract will keep the reward GAS for governance voters. For governance requirements, please refer to https://docs.google.com/document/d/11iDJGpCDNrKmPQN8TOhmEqBlWZAOstH15j3Afc2xoQo/edit#heading=h.idvp9uir3xt8.

The `GovernanceVote` contract is an abstract contract for Policy and other contracts (like `GovProxyAdmin`) who need a 1/2 consensus vote to execute some function.

We will use upgradable contracts for Governance, Policy and GovReward, `ERC1967Proxy` is used as proxy and `GovProxyAdmin` is used as the admin of upgrade.

For the implemention of #5, we will need following contracts in genesis alloc: 
1. GovProxyAdmin 0x1212000000000000000000000000000000000000
2. Governance Proxy 0x1212000000000000000000000000000000000001
3. Governance Implemention 0x1212100000000000000000000000000000000001
4. Policy Proxy 0x1212000000000000000000000000000000000002
5. Policy implemention 0x1212100000000000000000000000000000000002
6. Governance Reward 0x1212000000000000000000000000000000000003
7. Governance Reward implemention 0x1212100000000000000000000000000000000003

2023-09-11 07:31 UTC, txhsl approved these changes

2023-09-15 12:14 UTC, ZhangTao1596 commented on contracts/solidity/Governance.sol
> +                startHeight: draft.startHeight,
Check draft.startHeight > block.number here?

2023-09-15 12:15 UTC, ZhangTao1596 commented on contracts/solidity/Policy.sol
> +    function initialize()public{
format

2023-09-15 12:16 UTC, ZhangTao1596 commented on contracts/solidity/Policy.sol
> +	}
format

2023-09-18 06:51 UTC, txhsl commented on contracts/solidity/Policy.sol
> +    EnumerableSet.AddressSet  blackList;
Do we need the `blackList` and `getBlackList()` since we already have the map `isBlackListed`? I don't find them in Neo's Policy contract.

2023-09-18 08:49 UTC, Tobeyw commented on contracts/solidity/Policy.sol
> +    EnumerableSet.AddressSet  blackList;
#16

2023-09-18 08:53 UTC, Tobeyw commented on contracts/solidity/Policy.sol
> +	}
#17

2023-09-19 02:33 UTC, chenquanyu commented on contracts/solidity/Policy.sol
add events for policy contract

2023-09-19 07:38 UTC, chenquanyu commented on contracts/solidity/Governance.sol
> +                startHeight: draft.startHeight,
fixed in commit a6fdfc5767bdc56ca421fd83c26f8f1df607b484

2023-11-09 09:34 UTC, cloud8little reviewed
https://github.com/bane-labs/go-ethereum/pull/7/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R36
GOBIN -> GETHBIN

2023-11-10 10:16 UTC, nicolegys requested changes

2023-11-10 10:16 UTC, nicolegys commented on genesis.json
> +      "code": "0x608060405234801561001057600080fd5b50611514806100206000396000f3fe6080604052600436106100705760003560e01c80637eff275e1161004e5780637eff275e1461011a5780639623609d1461014357806399a88ec414
The `code` should be runtime bytecode.

2023-11-16 03:01 UTC, nicolegys commented on contracts/solidity/GovProxyAdmin.sol
> +        needVote(
`{GovProxyAdmin}` is the admin of `{Governance Proxy}`, and it cannot fallback to `{Governance Proxy}`. However, `needVote` calls `{Governance.getCurrentPhase}`, so the execution will be reverted.

2023-11-16 03:29 UTC, chenquanyu commented on contracts/solidity/GovProxyAdmin.sol
> +        needVote(
Yes, ProxyAdmin can not call fallback methods in Proxy. I will add a middle contract(GovReward.sol) to read governance voters.

2023-11-27 08:26 UTC, nicolegys commented on contracts/solidity/Governance.sol
> +        Draft[] memory drafts = new Draft[](count);
Call to `getDraftList` errored when there was no draft
![image](https://github.com/bane-labs/go-ethereum/assets/43694095/fd6cc462-b958-4829-ae20-5da6498ec68c)
Because in the initial state, startDraftId=1, endDraftId=0

2023-11-27 10:17 UTC, chenquanyu commented on contracts/solidity/Governance.sol
> +        Draft[] memory drafts = new Draft[](count);
Fixed by changing the order, please help to check the new logic of voting too.

2023-11-27 10:19 UTC, chenquanyu commented on contracts/solidity/GovProxyAdmin.sol
> +        needVote(
> `{GovProxyAdmin}` is the admin of `{Governance Proxy}`, and it cannot fallback to `{Governance Proxy}`. However, `needVote` calls `{Governance.getCurrentPhase}`, so the execution will be reverted.
Please verify this with new genesis.json file.

2023-12-01 07:37 UTC, nicolegys commented on contracts/solidity/Governance.sol
> +    function getRewardAmount(
The contract updates `lastStartHeight` and `rewardRecord` when vote passes, not when new phase starts, and there is a transition time between vote-pass and phase-start. 
`getRewardAmount` function returns different results when a voter calls it before and after a new draft passes, the latter amount is smaller.
So if someone had withdrawed his reward at `phase N - no draft passes`, then tries to withdraw again at `phase N - new draft passes`, there will be an underflow error.

2023-12-01 08:06 UTC, chenquanyu commented on contracts/solidity/Governance.sol
> +    function getRewardAmount(
Fixed by changing the current phase to last phase. 
`Phase memory current = phaseMap[lastStartHeight]`

2023-12-01 10:40 UTC, nicolegys commented
From the user's point of view, there is no function for users to get their voted draftIds. If someone has voted for several proposals in the past phases, he must walk through the previous transactions to find the draftIds and then get his ethers back (Unless he wrote them down somewhere by himself).

2023-12-01 10:43 UTC, nicolegys commented on contracts/solidity/Governance.sol
> +    function getRewardAmount(
> Fixed by changing the current phase to last phase. `Phase memory current = phaseMap[lastStartHeight]`

I'll test it again.

2023-12-05 07:54 UTC, nicolegys commented on contracts/solidity/Governance.sol
> +            IGovReward(govReward).withdraw(msg.sender, reward);
```suggestion
            IGovReward(govReward).withdraw(msg.sender, reward);
            emit WithdrawReward(msg.sender, reward);
```

2023-12-11 03:49 UTC, nicolegys commented on privnet/node2/genesis_privnet.json
> +        "0x0000000000000000000000000000000000000000000000000000000000000000": "0x989680",
```suggestion
        "0x0000000000000000000000000000000000000000000000000000000000000001": "0x989680",
```

2023-12-11 03:49 UTC, nicolegys commented on genesis.json
> +        "0x0000000000000000000000000000000000000000000000000000000000000000": "0x989680",
```suggestion
        "0x0000000000000000000000000000000000000000000000000000000000000001": "0x989680",
```

2023-12-11 03:49 UTC, nicolegys commented on privnet/node1/genesis_privnet.json
> +        "0x0000000000000000000000000000000000000000000000000000000000000000": "0x989680",
```suggestion
        "0x0000000000000000000000000000000000000000000000000000000000000001": "0x989680",
```

2023-12-19 09:52 UTC, nicolegys commented
merge?

2023-12-20 11:01 UTC, chenquanyu commented
> From the user's point of view, there is no function for users to get their voted draftIds. If someone has voted for several proposals in the past phases, he must walk through the previous transactions to find the draftIds and then get his ethers back (Unless he wrote them down somewhere by himself).

May be will need a UI for users to vote, and will list all the voted draft from event log.

2024-01-22 17:36 UTC, AnnaShaleva commented on Makefile
> +NODE1_HTTP_PORT = 8545
Can't we reuse `NODEX_RPC_PORT` variable to set `--http.port`? This Makefile is already complicated.

2024-01-22 17:36 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +    receive() external payable {}
Why do we need an empty-arguments receive? According to https://docs.soliditylang.org/en/latest/contracts.html#receive-ether-function, this function will be executed on a call to the contract with empty calldata. I don't think we should allow such transfers to the contract. But maybe I'm missing something.

2024-01-22 17:36 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +        require(isMiner(msg.sender), "Not Consensus");
Could we make error messages more verbose? Maybe at least something like "Sender is not a consensus member" for this case? It's a user-facing thing.

2024-01-22 17:36 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +        require(miners.length > 0, "invalid miners lenght");
What's the number of validators `Draft` can be created for? Don't we restrict it in any way?

2024-01-22 17:36 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +            "propose should after last phase active"
`Propose should be called after last phase start` or `Last phase is not active yet, proposing is prohibited`?

2024-01-22 17:36 UTC, AnnaShaleva commented on privnet/four/genesis_template.json
> +      "balance": "0",
We need to update not only template files, but also all `genesis_privnet.json` files.

2024-01-22 17:36 UTC, AnnaShaleva commented on genesis.json
> +{
Why do we need this new `genesis.json` file?

2024-01-22 17:36 UTC, AnnaShaleva commented on privnet/four/genesis_template.json
> +      "balance": "0",
And please, rebase onto current bane-main. There are seven-nodes privnet configurations available.

2024-01-22 17:36 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +    uint public endDraftId;
I see that you set the default values in the genesis allocations. How do you define the DB prefixes for these values? (`0x0000000000000000000000000000000000000000000000000000000000000000`, etc.)

Are you sure that these prefixes won't change after contract version update? We probably need to add some comment about it to the contract's code, because we need to keep these values in sync with genesis configuration.

2024-01-22 17:36 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +        }
A style comment: how about initializing `startDraftId` with `0`, `endDraftId` with `0`, and starting drafts enumeration from `0`? Then you won't have problems with indexes and here it will be possible to use `uint count = endDraftId - startDraftId` and the following:
```
        for (uint i = 0; i < endDraftId; i++) {
            drafts[i] = draftMap[i];
        }
```

2024-01-22 17:36 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +        uint256 draftId,
Why `draftId` has `uint256` type here and `uint` type in the struct declaration?

2024-01-22 17:36 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +        draftVoterMap[draftId][msg.sender] += amount;
But what if `msg.value` is *greater* than `amount`? Shouldn't we add `msg.value` instead of `amount`?

2024-01-22 17:36 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +        if (votedBalance >= VOTE_TARGET_AMOUNT) {
Currently we don't have a way to customize `VOTE_TARGET_AMOUNT`, it's hard-coded. However, I'd suggest to consider the way to customize it (some setter with restricted set of callers). What do you think?

2024-01-22 17:36 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +                totalWithdrawedReward;
OK, I see that we can track only voters reward balance, not the CNs miners reward that is transferred to the governance contract (also docs warns about it in the "Warning" section: https://docs.soliditylang.org/en/latest/contracts.html#receive-ether-function). But what if we store voter's reward balance in the contract and then the diff between `govReward.balance` and the actual value would be the CNs reward.

2024-01-22 17:36 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +        draftVoterMap[draftId][msg.sender] += amount;
OK, I see there's refund in the end.

2024-01-22 17:36 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +                totalWithdrawedReward;
Also, I think we need to be careful with ` govReward.balance` usage here anyway. We should prohibit no-data transfers to this contract.

2024-01-22 17:36 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +    uint public lastStartHeight;
Do we have a Phase duration constraint in the contract?

2024-01-22 17:36 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +    function getPhaseByHeight(uint height) external view returns (Phase memory);
Correct me if I'm wrong, please. AFAIU, this method returns the current `Phase` which contains `address[] miners` which is the list of current network validators. This list remains constant throughout the whole Phase (is it true?). This method will be used by dBFT engine to retrieve current block validators that should sign the subsequent block. However, as you know, dBFT should include NextConsensus address in the block which is a hashed flattened list of validators for the next block. In case of middle-epoch block next block validators match the current block validators, but for the last block in the epoch we need an ability to retrieve validators list for the next block. based on the current contract storage state. Currently I don't see the functionality for this in the contract.

2024-01-23 02:37 UTC, chenquanyu commented on contracts/solidity/Governance.sol
> +    function getPhaseByHeight(uint height) external view returns (Phase memory);
`getPhaseByHeight` can be used to get `NextConsensus ` by passing the next block height. `getCurrentPhase` is used to get current Phase.

2024-01-23 03:28 UTC, chenquanyu commented on contracts/solidity/Governance.sol
> +    uint public lastStartHeight;
No, the Phase duration depends on voting process.

2024-01-23 03:28 UTC, chenquanyu commented on contracts/solidity/Governance.sol
> +    uint public endDraftId;
The prefixes are fixed if the type and order are fixed. They are set in genesis file, please refer to this article https://medium.com/@flores.eugenio03/exploring-the-storage-layout-in-solidity-and-how-to-access-state-variables-bf2cbc6f8018. We can also get the prefixes from Remix storage after initialing them in `constructor`.

2024-01-23 03:28 UTC, chenquanyu commented on contracts/solidity/Governance.sol
> +    receive() external payable {}
Yes, we only need `vote()` to be payable for now.

2024-01-23 03:28 UTC, chenquanyu commented on contracts/solidity/Governance.sol
> +        require(miners.length > 0, "invalid miners lenght");
Now we don't restrict it, I don't know how many we should restrict.

2024-01-23 03:28 UTC, chenquanyu commented on contracts/solidity/Governance.sol
> +        }
`0` is the default value of `uint` in solidity, sometimes the same as null, so I avoid using it in not null value.

2024-01-23 03:28 UTC, chenquanyu commented on contracts/solidity/Governance.sol
> +        uint256 draftId,
uint and uint256 are the same type, will unify it.

2024-01-23 03:28 UTC, chenquanyu commented on contracts/solidity/Governance.sol
> +        if (votedBalance >= VOTE_TARGET_AMOUNT) {
If it can be set by validators, maybe we can set it in policy contract.

2024-01-23 03:28 UTC, chenquanyu commented on Makefile
> +NODE1_HTTP_PORT = 8545
We don't need http open in dev mode, will remove it.

2024-01-23 03:28 UTC, chenquanyu commented on genesis.json
> +{
Will remove it.

2024-01-23 07:58 UTC, AnnaShaleva commented on privnet/four/genesis_template.json
> +      "balance": "0",
You're right, this tremendous  set of genesis config files is a mess. Will be improved after #112 merge.

2024-01-23 09:30 UTC, AnnaShaleva reviewed
Oh, the PR was updated, so I'm leaving existing comments here for now and continue review once my review is re-requested.

@chenquanyu, please, tag me once you finish adjustments.

2024-01-23 09:30 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +    receive() external payable {}
Then let's remove it.

2024-01-23 09:30 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +    uint public endDraftId;
Good,thanks! Then we need to add a comment to this block of fields requiring genesis storage initialisation. The comment should contain a note about the fact that we should preserve the order of these fields and we should keep these values in sync with genesis configuration, it's important.

2024-01-23 09:30 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +        require(isMiner(msg.sender), "Not Consensus");
Do you have an updated version of code? I see your reactions, but the code isn't changed, so probably you forgot to push new commits?

2024-01-23 09:30 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +    uint public lastStartHeight;
But according to the "NeoX Governance Discussion":
>During each sidechain election period (which lasts one epoch, approximately 7 days), a total of 7 nodes are elected as consensus nodes, with 1 node becoming the block-producing node (Speaker) and 6 witness nodes (DBFT).

Do we have our Governance proposal updated? If https://docs.google.com/document/d/11iDJGpCDNrKmPQN8TOhmEqBlWZAOstH15j3Afc2xoQo/edit?mode=html is a latest relevant version then we need to modify contract code. If it's an outdated link, then please, provide the relevant one.

To restrict epoch duration I'd propose to bind to the number of blocks (not to the time period). So given 15-seconds blocks we need to use  `(7 * 24 * 60 * 60) / 15 = 40320` blocks as one epoch and Governance contract should be aware of it.

2024-01-23 09:30 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +    function getPhaseByHeight(uint height) external view returns (Phase memory);
Good, we need to test it during #14 implementation.

2024-01-23 09:30 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +        require(miners.length > 0, "invalid miners lenght");
According to the https://docs.google.com/document/d/11iDJGpCDNrKmPQN8TOhmEqBlWZAOstH15j3Afc2xoQo/edit?mode=html we need 7 validators for every epoch. This value is immutable within a network scope, and thus, can be moved to a variable those state can be setup via genesis allocations.

2024-01-23 09:30 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +    uint public constant VOTE_TARGET_AMOUNT = 3000000 ether;
This value is not fixed in the [proposal](https://docs.google.com/document/d/11iDJGpCDNrKmPQN8TOhmEqBlWZAOstH15j3Afc2xoQo/edit?mode=html). We either need to make it customizable by validators via restricted setters or we need to agree on this in Governance.

2024-01-23 09:30 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +                require(miners[i] < miners[i + 1], "invalid miners order");
According to [proposal](https://docs.google.com/document/d/11iDJGpCDNrKmPQN8TOhmEqBlWZAOstH15j3Afc2xoQo/edit?mode=html) for every proposed miner it should be true that:
> Stakes a deposit of 1000 GAS in the NeoX governance interface, which will be returned upon normal node exit (with a tentative locking period of one month equivalent to the same number of blocks).

I think this check should be presented on the contract level.

2024-01-23 09:30 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +        require(draftId <= endDraftId, "invalid draftId");
Shouldn't we require `draftId == endDraftId`? `revokeVote` is allowed for the latest in-progress draft, right?

Because according to the [proposal](https://docs.google.com/document/d/11iDJGpCDNrKmPQN8TOhmEqBlWZAOstH15j3Afc2xoQo/edit?mode=html):
> It is necessary to re-vote during each epoch (TBD, re-vote is easier for calculate the fee reward),

So after every epoch all previous votes should be automatically revoked. But this code is currently not implemented in the contract.

And to be honest, I'd propose not to perform automatic votes revoking after every epoch, because it might be complicated for the users to perform voting every week. It may decrease motivation to vote. And I think we can safely handle voters rewards without automatic revoking in the end of every epoch. @roman-khimov @txhsl @chenquanyu and everyone interested, need your opinion here.

2024-01-23 09:31 UTC, chenquanyu commented on contracts/solidity/Governance.sol
> +                totalWithdrawedReward;
> But what if we store voter's reward balance in the contract and then the diff between govReward.balance and the actual value would be the CNs reward.

All the transaction fee reward will be sent to `govReward` contract, the governance contract only keeps the Gas for voting.

2024-01-23 09:35 UTC, chenquanyu commented on contracts/solidity/Governance.sol
> +        require(draftId <= endDraftId, "invalid draftId");
> because it might be complicated for the users to perform voting every week

User don't need to vote unless they want to change the consensus, the phase has no time limit. I think we should update the [proposal](https://docs.google.com/document/d/11iDJGpCDNrKmPQN8TOhmEqBlWZAOstH15j3Afc2xoQo/edit?mode=html) first.

2024-01-23 09:37 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +        require(draftId <= endDraftId, "invalid draftId");
But how about initial Governance proposal? See the https://github.com/bane-labs/go-ethereum/pull/7#discussion_r1462941106.

2024-01-23 09:47 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +        require(draftId <= endDraftId, "invalid draftId");
> I think we should update the [proposal](https://docs.google.com/document/d/11iDJGpCDNrKmPQN8TOhmEqBlWZAOstH15j3Afc2xoQo/edit?mode=html) first.

Agree, let's discuss this set of proposal-related issues on the synchonisation meeting tomorrow. We need a single view of the desired Governance model to properly review this PR.

2024-03-15 04:06 UTC, chenquanyu commented on contracts/solidity/Governance.sol
> +    uint public constant VOTE_TARGET_AMOUNT = 3000000 ether;
We may set this to policy contract, the values in policy conract are voted by validators.

2024-03-26 11:19 UTC, AnnaShaleva commented on contracts/solidity/GovReward.sol
> +pragma solidity ^0.8.0;
Do we really need the previous version of GovReward and Governance contracts? We have V2 now, and V1 is never used.

2024-03-26 11:19 UTC, AnnaShaleva commented on contracts/solidity/GovernanceVote.sol
> +    mapping(bytes32 => mapping(address => bytes32)) private voteMap;
I think we need some kind of expiration for voting proposals. To clear expired (too old and useless) vote requests.

2024-03-26 11:19 UTC, AnnaShaleva commented on contracts/solidity/GovernanceVote.sol
> +        require(isMiner(msg.sender), "Not Miner");
Consider situation: if some validator votes for some method, but not enough votes are collected and vote request is still pending. Then next epoch is coming and validators set is being recalculated and changed. Then `voteMap` contains stale votes from previous validators, whereas technically it's correct to remove old votes from previous validator set and start to collect new votes from the new epoch validators.

2024-03-26 11:19 UTC, AnnaShaleva commented on contracts/solidity/GovernanceVote.sol
> +        return votedCount > (voters.length * 2) / 3;
Why do we use dBFT threshold here for policy? Shouldn't it be the majority-style agreement, i.e. `(N+1)/2`, like in Neo3?

2024-03-26 11:19 UTC, AnnaShaleva commented on genesis.json
> +{
This `genesis.json` file should be removed. We have `/config/genesis_testnet.json` file that should include contracts for T3-specific values, and we have a set of genesis files for privnet that should also be updated with the final contracts versions.

But this may be done once all our contracts are finalized.

2024-03-26 11:31 UTC, AnnaShaleva commented on contracts/solidity/Policy.sol
> +        isBlackListed[_addr] = false;
Just remove from `isBlackListed`? No need to store it in the map.

2024-03-27 02:26 UTC, chenquanyu commented on contracts/solidity/GovReward.sol
> +pragma solidity ^0.8.0;
I will keep only V2 as the GovReward and Governance contracts.

2024-03-27 02:31 UTC, chenquanyu commented on contracts/solidity/GovernanceVote.sol
> +    mapping(bytes32 => mapping(address => bytes32)) private voteMap;
Mapping is not traversable and it will cost more gas to find the expired keys.

2024-03-27 02:33 UTC, chenquanyu commented on contracts/solidity/GovernanceVote.sol
> +        require(isMiner(msg.sender), "Not Miner");
We calculate the votes with current consensus list, I think the vote from the same candidate at pre epoch should keep active in this epoch.

2024-03-27 03:13 UTC, chenquanyu commented on contracts/solidity/Policy.sol
> +        isBlackListed[_addr] = false;
They are nearly the same in solidity, please refer to https://ethereum.stackexchange.com/questions/44433/delete-an-entry-in-a-mapping. But I think `delete` is more readable.

2024-03-27 03:14 UTC, chenquanyu commented on genesis.json
> +{
Will remove it once our contracts are finalized.

2024-03-27 03:15 UTC, chenquanyu commented on contracts/solidity/GovernanceVote.sol
> +        return votedCount > (voters.length * 2) / 3;
I think both are OK, will change it if you think `(N+1)/2` is better.

2024-03-27 07:24 UTC, chenquanyu commented on genesis.json
> +{
I rollbacked the changes in genesis templates, will update them once contracts are finalized.

2024-03-27 10:04 UTC, AnnaShaleva commented on contracts/solidity/GovernanceVote.sol
> +    mapping(bytes32 => mapping(address => bytes32)) private voteMap;
But we have OnPersist, we may call *any* contract during OnPersist.

2024-03-27 10:04 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +            currentConsensus = standByValidators;
Good, it should work.

2024-03-27 10:23 UTC, nicolegys commented on contracts/solidity/Governance.sol
> +            currentConsensus = standByValidators;
So for epoch change, we expect to choose the standByValidators as consensus whenever there are not enough candidates/votes?

2024-03-27 11:24 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +            currentConsensus = standByValidators;
Yes, should be like this. Like in N3.

2024-03-29 09:31 UTC, AnnaShaleva reviewed
Seems that we have the final T3 contracts implementation here. Before we merge this PR, please, consider the following:
1. Let's squash commits into some logical blocks, because we need to keep our git history clear. For example, in commit 1 we may add all system contracts implementations, and in the commit 2 we may update all genesis files.
2. Ensure that contract hashes are correct  and relevant everywhere in the contracts and match the hashes described in https://github.com/bane-labs/go-ethereum/pull/7#issue-1877141548. I'll add the rest of them to `systemcontracts` package later.
3. Since contract implementation is final for T3, then we need to compile all contracts and update both T3 `genesis_testnet.json` file (`./config/genesis_testnet.json`) and privnet genesis files (`./privnet/*/genesis_privnet.json` and `./privnet/*/genesis_template.json`). Please, be careful with storage items since all genesis configuration files have different set of validators and different number of CNs.
4. `genesis.json` file should be removed.
5. Add `Close #5`, `Close #2`, `Close #3` to the PR message for proper GH issue links.

2024-03-29 14:39 UTC, chenquanyu commented on contracts/solidity/GovernanceVote.sol
> +    mapping(bytes32 => mapping(address => bytes32)) private voteMap;
This is an abstract contract, I'm not sure what should be expired vote requests. I think this should be hanlded by the contract that inherits this contract if needed.

2024-04-01 08:59 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +            if (receivedVotes[validators[i]] != 0) {
I think it's not quite correct to reward only user-chosen validators (but you may disagree, it's just my thought). In the start of the network we'll use stand by validators for some time before new candidates receive enough votes, and there will be some transactions in the network during this period of time. Should we reward stand by validators for that? I think yes, because they do their job, they accept blocks.

It's just about the fact that stand by validators don't share their reward with voters because they don't have voters. But in general, I think we should reward stand by validators if they are the current consensus.

2024-04-01 09:34 UTC, txhsl commented on contracts/solidity/Governance.sol
> +            if (receivedVotes[validators[i]] != 0) {
I think they are rewarded in this code, these lines of modification are checking whether a candidate has received any votes from voters, if not, then `candidateGasPerVote` will not be updated.
This `if` case only works for voter reward sharing, and the below down `_safeTransferETH` still works to transfer governance reward to block validators, regardless of if they are stand-by validators.

2024-04-01 09:47 UTC, txhsl commented on contracts/solidity/Governance.sol
> +            if (receivedVotes[validators[i]] != 0) {
Let me know if I'm wrong here😅.

2024-04-01 14:26 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +            if (receivedVotes[validators[i]] != 0) {
My bad, everything is OK here.

2024-04-05 16:29 UTC, nicolegys commented on contracts/solidity/Governance.sol
> +            _safeTransferETH(
So if one's `receivedVotes`==0, the share part of its rewards will stay in this contract forever? But this scenario doesn't seem to happen, because voters tend to get more rewards by voting for candidates with lower votes.

2024-04-05 16:30 UTC, nicolegys commented on contracts/solidity/Governance.sol
> +        if (length < consensusSize || totalVotes < voteTargetAmount) {
When some candidates exit, `totalVotes` won't decrease until their voters revoke vote. So the number of valid votes in the network may not be enough, but we still choose new consensus from the current candidates.

2024-04-05 16:40 UTC, txhsl commented on contracts/solidity/Governance.sol
> +            _safeTransferETH(
Yes, these rewards will be locked forever, or in another word, the same as be burned. The thing is, the candidate wants to share with its voters, but nobody can receive them. This happens when a stand-by validator registers as a normal candidate, set a none-zero `shareRate`, and is selected as a consensus member, if it is reasonable.

2024-04-05 16:44 UTC, txhsl commented on contracts/solidity/Governance.sol
> +        if (length < consensusSize || totalVotes < voteTargetAmount) {
Yes, it is an issue, but since there are few candidate exits on N3, we can fix this in the future if it is not urgent. I will create a new issue and another PR to fix it.

2024-04-09 04:03 UTC, chenquanyu commented
I have tested the `upgradeAndCall` in `GovProxyAdmin` and found the `reverted` error when calling to `UUPSUpgradeable` methods `proxiableUUID` and `upgradeToAndCall`. The root cause is `immutable __self` in `UUPSUpgradeable` is not avaliable in pre-compile contract.

2024-04-09 07:23 UTC, AnnaShaleva commented
> The root cause is immutable __self in UUPSUpgradeable is not avaliable in pre-compile contract.

Is this fact connected with the way how we deploy system contracts? I.e. some storage items are missing in genesis allocations?

2024-04-09 07:33 UTC, chenquanyu commented
> Is this fact connected with the way how we deploy system contracts? I.e. some storage items are missing in genesis allocations?

Immutable variables are evaluated once at construction time and their value is copied to all the places in the code where they are accessed. So it has nothing to do with storage, we are solving this problem by overriding these methods which use "immutable __self" variable.

2024-04-09 15:26 UTC, AnnaShaleva reviewed
LGTM otherwise.

2024-04-09 15:26 UTC, AnnaShaleva commented on contracts/solidity/Governance.sol
> +        if (length < consensusSize || totalVotes < voteTargetAmount) {
Issue, please.

2024-04-09 15:26 UTC, AnnaShaleva commented on config/genesis_testnet.json
> +}
Here and below no new line in the end of the file. Please, consider adding new line in the end.

2024-04-09 15:26 UTC, AnnaShaleva commented on config/genesis_testnet.json
> +    "0x1212000000000000000000000000000000000000": {
Why have you removed the initial balance from validator nodes? Is Steven OK with it?

2024-04-10 02:16 UTC, chenquanyu commented on config/genesis_testnet.json
> +    "0x1212000000000000000000000000000000000000": {
Yes, we want to simulate the case for mainnet.

2024-04-10 02:17 UTC, chenquanyu commented on config/genesis_testnet.json
> +}
It's formated by vs code, do we need the new line?

2024-04-10 02:27 UTC, chenquanyu commented on contracts/solidity/Governance.sol
> +        if (length < consensusSize || totalVotes < voteTargetAmount) {
New issue #161

2024-04-10 07:08 UTC, AnnaShaleva commented on config/genesis_testnet.json
> +}
OK, let's have it as is.

2024-04-10 07:10 UTC, AnnaShaleva approved these changes

2024-04-10 07:25 UTC, AnnaShaleva commented
@roman-khimov, @txhsl, @nicolegys, @ZhangTao1596 ready for the final review&merge.

2024-04-10 08:54 UTC, AnnaShaleva commented on contracts/solidity/Policy.sol
> +    }
BTW, it's just came to my mind, we need a getter for `minGASPrice` so that the external NeoX users who create transactions are able to properly retrieve this value to build good transaction with proper GAS price.

2024-04-10 08:55 UTC, AnnaShaleva commented on contracts/solidity/Policy.sol
> +    }
Since right now this setting is being enforced by the system.

2024-04-10 09:21 UTC, chenquanyu commented on contracts/solidity/Policy.sol
> +    }
I think we should change `eth_gasPrice` interface.

2024-04-10 09:51 UTC, AnnaShaleva commented on contracts/solidity/Policy.sol
> +    }
Let's have https://github.com/bane-labs/go-ethereum/issues/162 for this. But I think that getter should be added to Policy contract as far, in order to be able to get this value via "honest" contract invocation. @txhsl, @roman-khimov, what do you think?

2024-04-10 10:13 UTC, AnnaShaleva commented on contracts/solidity/Policy.sol
> +    }
I'm not talking about the immediate change, we may create an issue for that and plan it to 0.2.0 to be able to properly test the updated Policy version.

2024-04-10 12:36 UTC, chenquanyu commented on contracts/solidity/Policy.sol
> +    }
> But I think that getter should be added to Policy contract as far, in order to be able to get this value via "honest" contract invocation. @txhsl, @roman-khimov, what do you think?

The getter method is added by default in solidity for public fields, just call `minGasPrice()` with policy contract.

2024-04-11 07:10 UTC, chenquanyu commented
We have not yet added the function of burning fees. We can send part of fees to an empty address in the governance contract to burn and configure this burning ratio in the policy contract. Issue opened in #163.

2024-04-11 07:33 UTC, txhsl commented on config/genesis_testnet.json
> +        "0x0000000000000000000000000000000000000000000000000000000000000001": "0x989680",
I think we may improve this to at least 1 Gwei = 10^9, which is `0x3b9aca00`, or above, to 1.5 Gwei. The current T2 transactions are, `Gas fees (Gwei) Base: 0.000000007 | Max: 1.500000008 | Max priority: 1.5`, which means their basefee is `7 wei`, priority fee is `1.5 Gwei`, and their gas price is `1.500000007 Gwei`.

They are all accepted with `"gasPrice": "0x59682f07", "maxFeePerGas": "0x59682f08", "maxPriorityFeePerGas": "0x59682f00"`. In theory, their `GasFeeCap` is `1.500000008 Gwei` and `GasTipCap` is `1.5 Gwei`. Just mention this issue, I'm again looking at #6.

2024-04-11 10:49 UTC, AnnaShaleva commented on config/genesis_testnet.json
> +        "0x0000000000000000000000000000000000000000000000000000000000000001": "0x989680",
> I think we may improve this to at least 1 Gwei = 10^9, which is 0x3b9aca00, or above, to 1.5 Gwei. 

Maybe start with the lower value, with 1 Gwei? We can always adjust this value in Policy anyway.

2024-04-15 10:45 UTC, AnnaShaleva approved these changes
LGTM.

2024-04-15 20:57 UTC, mialbu reviewed
Minor documentation and consistency-related comments.

2024-04-15 20:57 UTC, mialbu commented on contracts/solidity/GovProxyAdmin.sol
> +     * {TransparentUpgradeableProxy-upgradeToAndCall}.
```suggestion
     * @dev Upgrades the implementation of the proxy to `newImplementation`, and subsequently executes the function call
     * encoded in `data`.
     * 
     * See {UUPSUpgradeable-upgradeToAndCall}.
```

2024-04-15 20:57 UTC, mialbu commented on contracts/solidity/GovProxyAdmin.sol
> +        address implementation,
Consider renaming this parameter to `newImplementation` for consistency.

2024-04-15 20:57 UTC, mialbu commented on contracts/solidity/GovProxyAdmin.sol
> +     * {TransparentUpgradeableProxy-upgradeToAndCall}.
Or

```suggestion
     * @dev Upgrades the implementation of the proxy to `implementation`, and subsequently executes the function call
     * encoded in `data`.
     * 
     * See {UUPSUpgradeable-upgradeToAndCall}.
```

2024-04-16 07:36 UTC, AnnaShaleva approved these changes

2024-04-16 07:42 UTC, merged